package DataAccessLayer;

public enum FoodType {
	FOOD_TYPE_BROCCOLI,
	FOOD_TYPE_CARROT,
	FOOD_TYPE_LETTUCE,
	FOOD_TYPE_CAKE,
	FOOD_TYPE_BROWNIES,
	FOOD_TYPE_MUFFIN,
	FOOD_TYPE_EGG,
	FOOD_TYPE_BREAD,
	FOOD_TYPE_CEREAL
}
